# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IPBYpS12BxG5Ojt_vG_O0dCja6lzIBTA

Importing libs
"""

import pandas as pd
import matplotlib.pyplot as plt

"""Reading colors.csv"""

colors = pd.read_csv("datas/colors.csv")
colors.head()

"""Number of colors(only unique ones)"""

colors['name'].nunique()

colors.groupby('is_trans').count()

"""Reading sets.csv file"""

sets = pd.read_csv("datas/sets.csv")
sets.tail()

sets.sort_values('year').head()

"""Yearly production of Lego by categories"""

sets[sets['year']==1949]

sets.sort_values('num_parts', ascending=False)

"""Number of parts that has been produced each year"""

sorted_by_year = sets.groupby('year').count()
plt.plot(sorted_by_year.index[:-2], sorted_by_year.set_num[:-2])

"""The number of themes for each year"""

themes_by_year = sets.groupby('year').agg({'theme_id': pd.Series.nunique})
plt.plot(sorted_by_year.index[:-2], themes_by_year[:-2])

"""two graphs above are in one below"""

ax1 = plt.gca()
ax2 = ax1.twinx()
ax1.plot(sorted_by_year.index[:-2], sorted_by_year.set_num[:-2], 'green')
ax2.plot(sorted_by_year.index[:-2], themes_by_year[:-2], 'b')

ax1.set_xlabel('Year')
ax1.set_ylabel('The number of sets', color='green')
ax2.set_ylabel('The number of themes', color='blue')

"""average number of parts for each year"""

parts_per_set = sets.groupby('year').agg({'num_parts': pd.Series.mean})
plt.scatter(parts_per_set.index[:-2], parts_per_set.num_parts[:-2])

set_theme_count = sets['theme_id'].value_counts()
set_theme_count = pd.DataFrame({'id': set_theme_count.index, 'set_count': set_theme_count.values})
set_theme_count.head()

"""sets and themes files merged here"""

plt.figure(figsize=(16,8))
plt.xticks(fontsize=14, rotation=45)
plt.yticks(fontsize=14)
plt.xlabel('Themes name', fontsize=14)
plt.ylabel('Number of sets', fontsize=14)
merged_df = pd.merge(set_theme_count, themes, on='id')
plt.bar(merged_df.name[:10], merged_df.set_count[:10])